name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        #os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v1

      - name: Install nodejs npm & yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/release Electrion app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # auto created without stating repo secret
          github_token: ${{ secrets.github_token }}
          # release app if commit tagged with version e.g 'v1.0.0
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
